### ISSUE TITLE
bed respawn when coming back from END

### ISSUE THREAD

**Issue by kryr34** [DeathGOD7/unexpectedspawn-paper#22]
I expect bed respawn when coming back to OVERWORLD from END,
but random respawn when the player dies.

IDK how to configure it or if it's possible.

P.S. I saw the msg `Using world (world) where player will respawn normally. Probably coming back to OVERWORLD from END.`, but unsure how it helps.

<details>
<summary>my config now</summary>

```yml
random-respawn:
  on-death: true
  bed-respawn-enabled: false
  on-first-join: true
  always-on-join: false
```

</details>

**Comment by RexSE7EN** [comment]
Please turn the bed respawn to true in config.

````yaml
random-respawn:
  on-death: true
  bed-respawn-enabled: true
  on-first-join: true
  always-on-join: false
````
